name: climora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  speech_to_text: ^7.3.0
  firebase_core: ^3.3.0 # Required for all Firebase packages
  firebase_auth: ^5.1.2 # To get the current user
  flutter_tts: ^4.2.5
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  http: ^1.2.0
  flutter_dotenv: ^6.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  sqflite: ^2.4.1
  path: ^1.9.1
  cloud_firestore: ^5.1.0 # To interact with Firestore
  file_picker: ^10.3.10
  url_launcher: ^6.3.1
  google_fonts: ^8.0.2

dependency_overrides:
  meta: ^1.18.1
  win32: ^6.0.0
  unicode: ^1.1.9
  proj4dart: ^3.0.0
  mgrs_dart: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/music/
